stages:
    - build
    - test
build:
    stage: build
    tags:
        - docker
    script:
        - mkdir build && cd build
        - cmake .. && make
test:
    stage: test
    tags:
        - docker
    script:
        - find . -name '*.c' | xargs wc -l
        - mkdir build && cd build
        - cmake .. && make
        - cp /usr/src/app/script.sh .
        - valgrind --leak-check=full --error-exitcode=1 ./42sh script.sh