stages:
    - Build
    - Lines counter
    - Tests
build:
    stage: Build
    tags:
        - docker
    script:
        - mkdir build && cd build
        - cmake .. && make
Functionnal Tests:
    stage: Tests
    tags:
        - docker
    script:
        - mkdir build && cd build
        - cmake .. && make debug
        - cp /usr/src/app/script.sh .
        - make script_test
lines_counter:
    stage: Lines counter
    tags:
        - docker
    script:
        - find . -name '*.c' | xargs wc -l
Clang Format:
    stage: Tests
    tags:
        - docker
    script:
        - cp /usr/src/app/clang-test.sh ./src/
        - cd src/
        - sh clang-test.sh
