stages:
    - Build
    - Post-build
    - Mandatory
build:
    stage: Build
    tags:
        - docker
    script:
        - mkdir build && cd build
        - cmake .. && make
Functionnal Tests:
    stage: Post-build
    tags:
        - docker
    script:
        - mkdir build && cd build
        - cmake .. && make debug
        - cp /usr/src/app/script.sh .
        - make script_test
Lines Counter:
    stage: Post-build
    tags:
        - docker
    script:
        - find . -name '*.c' | xargs wc -l
Clang Format:
    stage: Post-build
    tags:
        - docker
    script:
        - cp /usr/src/app/clang-test.sh ./src/
        - cd src/
        - sh clang-test.sh
Trailing Whitespaces:
    stage: Mandatory
    tags:
        - docker
    script:
        - pre-commit install
        - pre-commit run --all-files
