repos:
- repo: local
  hooks:
  - id: clang-format
    name: coding style
    entry: clang-format --Werror --dry-run
    language: system
    files: \.(c|h)$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
